# Generated by Django 2.2.6 on 2019-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
