# Generated by Django 2.2.6 on 2019-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0002_usermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
