# Generated by Django 2.2.6 on 2019-11-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0004_auto_20191120_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='mobile_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lucky.SignUp'),
            preserve_default=False,
        ),
    ]
