# Generated by Django 2.2.6 on 2019-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0005_usermaster_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
