# Generated by Django 2.2.6 on 2019-11-21 12:03

from django.db import migrations
import lucky.models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0006_signup_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
                ('objects', lucky.models.UserManager()),
            ],
        ),
    ]
