# Generated by Django 2.2.6 on 2019-11-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0007_auto_20191121_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='signup',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
