# Generated by Django 2.2.6 on 2019-11-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0008_auto_20191122_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
