# Generated by Django 2.2.6 on 2019-11-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0009_auto_20191122_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
