# Generated by Django 2.2.6 on 2019-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0011_signup_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='is_admin',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='is_superuser',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='superuser'),
        ),
    ]
